import { BusInfo } from "./bus-info";
import { Passenger } from "./passenger";
import { User } from "./user";

export interface Ticket {

    ticket_id?: string;     // generated by backend
    uid: string;            // FK -> User
    bus_id: number;         // FK -> Bus

    travel_date: string;    // ISO string from backend
    booking_time: string;   // ISO string
    amt_paid: number;

    route: string
    status: StatusEnum;

    user?: User;            // Relationship
    bus?: BusInfo;              // Relationship
    passengers?: Passenger[];
}

export enum StatusEnum {
    cnf = 'Confirm',
    cancelled = 'Cancelled',
    failed = 'Failed'
}