services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: angular_frontend
    restart: always
    ports:
      - "80:80"
      #when running using terraform:
      #when running locally:
      #- "4200:80"
    depends_on:
      - backend
